Level999.Web/Controllers/BaseController.cs
using System.Web.Mvc;
using Level999.Web.Components.Filters;

namespace Level999.Web.Controllers
{
    [AuthenticationFilter]
    public class BaseController : Controller
    {
       

    }
}

Level999.Web/Controllers/EnterpriseController.cs
using System;
using System.Web.Mvc;
using Level999.Business.Controllers;
using Level999.Data.Common.Controllers;
using Level999.Web.Components;

namespace Level999.Web.Controllers
{
    public class EnterpriseController : BaseController
    {
        public ActionResult Entrance()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Entrance(string name, string email)
        {

            try
            {
                var sysa001 = Sysbsa001.Sysa001001(name, email);

                LocalSessionContext.GetCurrent().User = sysa001;
                return Json(new { status = "OK", redirect = Url.Action("Index", "Home") });
            }
            catch (Exception e)
            {
                return Json(new { status = "FAIL", message = e.Message });
            }                       
        }
    }
}

Level999.Web/Controllers/HomeController.cs
using System.Web.Mvc;
using Level999.Data.Common.Controllers;
using Level999.Web.Components;

namespace Level999.Web.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string user, string pass)
        {
            Logout();

            var sysa001 = Syscta001.Select(user);
            if (sysa001 != null)
            {
                if (sysa001.Sysa001Password != pass)
                    return Json(new { status = "FAIL" });

                LocalSessionContext.GetCurrent().User = sysa001;
                return Json(new { status = "OK", redirect = Url.Action("Index") });
            }
            return Json(new { status = "FAIL" });
        }

        public ActionResult GetProfile()
        {
            var user = LocalSessionContext.GetCurrent().User;
            user.Sysa001Password = null;
            return Json(new { status = "OK", data = user }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Logout()
        {
            if (LocalSessionContext.GetCurrent().User != null)
            {
                LocalSessionContext.GetCurrent().User = null;
            }
            return Json(new { status = "OK" });
        }
    }
}

Level999.Web/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Level999.Data.Common.Models;
using Level999.Web.Components;
using Microsoft.Ajax.Utilities;
using Level999.Data.Common.Controllers;

namespace Level999.Web.Controllers
{
    public class TasksController : BaseController
    {
        // GET: Tasks
        [HttpPost]
        public ActionResult Insert(string title, string description, string urgency, string importance, bool? sun, bool? mon, bool? tue, bool? wed, bool? thr, bool? fri, bool? sat)
        {
            if (string.IsNullOrEmpty(title))
                return Json(new { status = "FAIL", field = "title", message=  "Ei! Você precisa informar um título para a tarefa."});

            //if (string.IsNullOrEmpty(description))
            //    return Json(new { status = "FAIL", field = "description" });

            if (string.IsNullOrEmpty(urgency))
                urgency = "0";
            //return Json(new { status = "FAIL", field = "urgency" });

            if (string.IsNullOrEmpty(importance))
                importance = "0";
            //return Json(new { status = "FAIL", field = "importance" });

            int auxUrgency = int.MinValue;
            if (!int.TryParse(urgency, out auxUrgency))
                auxUrgency = 0;
            //return Json(new { status = "FAIL", field = "urgency" });

            int auxImportance = int.MinValue;
            if (!int.TryParse(importance, out auxImportance))
                auxImportance = 0;
            //return Json(new { status = "FAIL", field = "importance" });


            var tska001 = new Tska001()
            {
                Tska001Sysa001Id = LocalSessionContext.GetCurrent().User.Sysa001Id,
                Tska001Title = title,
                Tska001Description = description,
                Tska001Urgency = auxUrgency,
                Tska001Importance = auxImportance,
                Tska001Sun = sun.HasValue ? 1 : 0,
                Tska001Mon = mon.HasValue ? 1 : 0,
                Tska001Tue = tue.HasValue ? 1 : 0,
                Tska001Wed = wed.HasValue ? 1 : 0,
                Tska001Thr = thr.HasValue ? 1 : 0,
                Tska001Fri = fri.HasValue ? 1 : 0,
                Tska001Sat = sat.HasValue ? 1 : 0,
                Tska001Points = "0",
                Tska001Type = "D"
            };

            Tskcta001.Insert(tska001);

            return Json(new { status = "OK", model = tska001 });
        }

        public ActionResult List()
        {
            var taskList = Tskcta001.List(LocalSessionContext.GetCurrent().User.Sysa001Id);

            return Json(new { status = "OK", list = taskList }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Finish(long id)
        {
            Tskcta001.UpdateFinished(id);

            return Json(new { status = "OK", dateFinished = DateTime.Now }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            Tskcta001.UpdateDeleted(id);

            return Json(new { status = "OK" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Level999.Web/Views/Enterprise/Entrance.cshtml
@{
    ViewBag.Title = "level999 - Entrada";
}
@section pageCss{
    <link rel="stylesheet" href="@Url.Content("~/Content/pages/home/entrance.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/css/libs/angular-typed/angular-typed.css")">
}
@section pageScripts{
    <script src="@Url.Content("~/Content/js/app/services/enterprise-service.js")"></script>
    <script src="@Url.Content("~/Content/js/app/controllers/entrance-controller.js")"></script>
}

<div class="container-fluid h-100" ng-controller="entranceController" ng-init="onInit()">
    <div class="row">
        <div class="col p-3 animate-down text-center bg-light" ng-show="formShow">
            <h2>
                <div>
                    <img class="img-fluid" src="@Url.Content("~/Content/img/app/ludotask-logo.png")" style="width: 120px;">
                </div>
                Capítulo 1. Uma nova jornada!
            </h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-8 animate-down" ng-show="formShow">
            <div class="p-5">
                <div class="text-xxxl text-primary pb-5" typed type-speed="5" start-timeout="2000" endline-timeout="1500" remove-line="false" html-mode type-strings="model.chats"></div>
                <!--<div class="row mb-4">
                    <div class="col-12 text-center">
                        <a class="btn btn-block btn-raised btn-primary ink-reaction" href="@Url.Action("Entrance", "Enterprise")">Comece a sua jornada!</a>
                    </div>
                </div>-->
            </div>
        </div>
    </div>
</div>

Level999.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "LudoTask - Início";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}
@section pageScripts{
    <script src="@Url.Content("~/Content/js/game/core.js")"></script>
    <script src="@Url.Content("~/Content/js/game/components.js")"></script>
    <script src="@Url.Content("~/Content/js/game/scenes/main.js")"></script>
}
<div ng-view class="h-100"></div>

Level999.Web/Views/Home/Login.cshtml
@{    
    ViewBag.Title = "level999 - Entrada";
}
@section pageCss{
    <link href="https://fonts.googleapis.com/css?family=Fondamento" rel="stylesheet">
    <link rel="stylesheet" href="@Url.Content("~/Content/pages/home/login.css")">
}
@section pageScripts{
    <script src="@Url.Content("~/Content/js/app/controllers/login-controller.js")"></script>
    <script src="@Url.Content("~/Content/js/game/core.js")"></script>
    <script src="@Url.Content("~/Content/js/game/components.js")"></script>
    <script src="@Url.Content("~/Content/js/game/scenes/login.js")"></script>
}
<div class="row h-100 m-0" ng-controller="loginController" ng-init="onFormInit()">
    <div class="col-xs-12 col-md-4 h-100 p-5 bg-light animate-left" ng-show="formShow">
        <div class="d-flex flex-column justify-content-center h-100 p-5">
            <h1 class="display-4 text-center">
                <img src="@Url.Content("~/Content/img/app/ludotask-logo.png")">
            </h1>
            <p class="lead">Essa plataforma irá te proporcionar uma <strong>nova experiência</strong> para se manter <strong>motivado</strong> na conclusão de suas tarefas, <strong>otimização</strong> do seu tempo e ainda se <strong>divertindo</strong>.</p>
            <div class="row mb-4">
                <div class="col-12 text-center">
                    <a class="btn btn-block btn-raised btn-primary ink-reaction" href="@Url.Action("Entrance", "Enterprise")">Comece a sua jornada!</a>
                    <!--<p class="text-light">
                        ou
                    </p>
                    <p>
                        <a href="#" class="btn btn-block btn-raised btn-info"><i class="fa fa-facebook pull-left"></i>Acesse com Facebook</a>
                    </p>
                    <p>
                        <a href="#" class="btn btn-block btn-raised btn-info"><i class="fa fa-google pull-left"></i>Acesse com Google</a>
                    </p>-->
                </div><!--end .col -->
            </div><!--end .col -->
            <form class="form" method="post" ng-submit="onFormSubmit('@Url.Action("Login", "Home")')">
                <div class="form-group floating-label">
                    <input type="text" class="form-control" id="user" name="user" ng-model="formData.user">
                    <label for="user">Usuário</label>
                </div>
                <div class="form-group floating-label">
                    <input type="password" class="form-control" id="senha" name="senha" ng-model="formData.pass">
                    <label for="senha">Senha</label>
                    <!--<p class="help-block"><a href="#">Esqueceu?</a></p>-->
                </div>
                <div class="form-row">
                    <div class="form-group col-10">
                    <!--    <div class="text-left">
                            <div class="checkbox checkbox-inline checkbox-styled">
                                <label>
                                    <input type="checkbox"> <span>Lembrar</span>
                                </label>
                            </div>
                        </div>-->
                    </div>
                    <div class="form-group col-2">
                        <div class="text-right">
                            <button class="btn btn-default btn-raised ink-reaction" type="submit">Acessar</button>
                        </div><!--end .col -->
                    </div><!--end .col -->
                </div><!--end .row -->
            </form>
        </div>

    </div>
    <div id="level999-game" class="col h-100 p-0 animate-right" ng-show="gameShow">
    </div>
</div>

Level999.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="lvl999App">
<head>
    <title>@ViewBag.Title</title>

    <!-- BEGIN META -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="your,keywords">
    <meta name="description" content="Short explanation about this website">
    <base href="/" />

    <!-- BEGIN STYLESHEETS -->
    <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800' rel='stylesheet' type='text/css'/>-->
    <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,500,700" rel="stylesheet">
    @Styles.Render("~/Content/css/defaults")
    @Styles.Render("~/Content/css/fonts")
    <!-- Additional CSS includes -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script type="text/javascript" src="@Url.Content("~/Content/js/libs/utils/html5shiv.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/js/libs/utils/respond.min.js")"></script>
    <![endif]-->
    @RenderSection("pageCss", false)
</head>

<body class="menubar-hoverable header-fixed">
    @RenderBody()
    <!-- BEGIN JAVASCRIPT -->
    <script src="@Url.Content("~/Content/js/libs/jquery/jquery-1.11.2.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/jquery/jquery-migrate-1.2.1.min.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.8.2/umd/popper.js"></script>
    <script src="@Url.Content("~/Content/js/libs/bootstrap/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/nanoscroller/jquery.nanoscroller.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/phaser/phaser.min.js")"></script>
   
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js" asp-fallback-src="@Url.Content("~/Content/js/libs/angular/angular.min.js")" asp-fallback-test="window.angular"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.min.js"></script>
    @Scripts.Render("~/Content/js/material")
    @RenderSection("pageModules", false)
    <script src="@Url.Content("~/Content/js/app/module.js")"></script>
    @RenderSection("pageScripts", false)
</body>
</html>

Level999.Web/Views/Shared/_LayoutIndex.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="lvl999App">
<head>
    <title ng-bind="Title"></title>

    <!-- BEGIN META -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="your,keywords">
    <meta name="description" content="Short explanation about this website">
    <base href="/" />

    <!-- BEGIN STYLESHEETS -->
    <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800' rel='stylesheet' type='text/css'/>-->
    <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,500,700" rel="stylesheet">
    @Styles.Render("~/Content/css/defaults")
    @Styles.Render("~/Content/css/fonts")
    <!-- Additional CSS includes -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script type="text/javascript" src="@Url.Content("~/Content/js/libs/utils/html5shiv.js")"></script>
        <script type="text/javascript" src="@Url.Content("~/Content/js/libs/utils/respond.min.js")"></script>
    <![endif]-->
    @RenderSection("pageCss", false)
</head>

<body class="header-fixed full-content" ng-controller="mainController" ng-init="onInit()">
    <div class="h-100">
        <lvl999-header profile="model.profile"></lvl999-header>
        @RenderBody()
    </div>
    <!-- BEGIN JAVASCRIPT -->
    <script src="@Url.Content("~/Content/js/libs/jquery/jquery-1.11.2.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/jquery/jquery-migrate-1.2.1.min.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.8.2/umd/popper.js"></script>
    <script src="@Url.Content("~/Content/js/libs/bootstrap/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/nanoscroller/jquery.nanoscroller.min.js")"></script>
    <script src="@Url.Content("~/Content/js/libs/phaser/phaser.min.js")"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js" asp-fallback-src="@Url.Content("~/Content/js/libs/angular/angular.min.js")" asp-fallback-test="window.angular"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-animate.min.js"></script>
    @Scripts.Render("~/Content/js/material")
    @RenderSection("pageModules", false)
    <script src="@Url.Content("~/Content/js/app/module.js")"></script>
    @RenderSection("pageScripts", false)
    <script src="@Url.Content("~/Content/js/app/services/home-service.js")"></script>
    <script src="@Url.Content("~/Content/js/app/services/tasks-service.js")"></script>
    <script src="@Url.Content("~/Content/js/app/controllers/main-controller.js")"></script>
    <script src="@Url.Content("~/Content/js/app/controllers/home-controller.js")"></script>
    <script src="@Url.Content("~/Content/js/app/controllers/inventory-controller.js")"></script>
    <script src="@Url.Content("~/Content/js/app/controllers/market-controller.js")"></script>
</body>
</html>